spin_version = "1"
authors = ["Elijah Sink <theminorprofit@gmail.com>"]
description = "A Spin HTTP component in Rust which plays Tic-Tac-Toe"
name = "spin-tac-toe"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "spin-tac-toe"
source = "target/wasm32-wasi/release/spin_tac_toe.wasm"
[component.trigger]
route = "/tic-tac-toe"
[component.build]
command = "cargo build --target wasm32-wasi --release"
